#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ASPX 到 Thymeleaf 完整转换脚本
支持：Shift-JIS 编码、图片路径转换、所有常见 asp 标签
用法: python aspx2thymeleaf_full.py input.aspx output.html
"""

import re
import sys
from pathlib import Path

# 尝试导入编解码器
try:
    import codecs
    # 注册 Shift-JIS 编码别名
    codecs.lookup('shift-jis')
except LookupError:
    pass

# ========== 配置 ==========
# 输入文件编码（根据实际情况修改）
INPUT_ENCODING = 'shift-jis'  # 或 'cp932' (Windows 日文编码)
OUTPUT_ENCODING = 'utf-8'

# 图片路径配置
IMG_PATH_MAPPING = {
    # 原始路径模式 -> Thymeleaf 路径
    r'~/images/': '@{/images/',
    r'~/img/': '@{/img/',
    r'~/Image/': '@{/image/',
    r'\.\./images/': '@{/images/',
    r'\.\./img/': '@{/img/',
    r'Images/': '@{/images/',
    r'images/': '@{/images/',
}

# ========== 完整标签映射表 ==========
TAG_MAP = {
    # 基本控件
    'asp:Label': 'span',
    'asp:TextBox': 'input',
    'asp:Button': 'button',
    'asp:LinkButton': 'a',
    'asp:ImageButton': 'button',
    'asp:HyperLink': 'a',
    'asp:Image': 'img',
    'asp:Panel': 'div',
    'asp:PlaceHolder': 'div',
    'asp:Literal': 'span',
    'asp:CheckBox': 'input',
    'asp:RadioButton': 'input',
    'asp:CheckBoxList': 'div',
    'asp:RadioButtonList': 'div',
    'asp:DropDownList': 'select',
    'asp:ListBox': 'select',
    'asp:BulletedList': 'ul',
    'asp:Table': 'table',
    'asp:TableRow': 'tr',
    'asp:TableCell': 'td',
    # 数据控件
    'asp:Repeater': 'div',
    'asp:GridView': 'table',
    'asp:DataList': 'div',
    'asp:ListView': 'div',
    'asp:DetailsView': 'table',
    'asp:FormView': 'div',
    # 验证控件
    'asp:RequiredFieldValidator': 'span',
    'asp:RegularExpressionValidator': 'span',
    'asp:CompareValidator': 'span',
    'asp:RangeValidator': 'span',
    'asp:ValidationSummary': 'div',
    'asp:CustomValidator': 'span',
    # 导航控件
    'asp:Menu': 'nav',
    'asp:TreeView': 'div',
    'asp:SiteMapPath': 'div',
    # 登录控件
    'asp:Login': 'form',
    'asp:LoginView': 'div',
    'asp:LoginStatus': 'div',
    'asp:CreateUserWizard': 'div',
    'asp:ChangePassword': 'form',
    # 其他
    'asp:Calendar': 'div',
    'asp:AdRotator': 'div',
    'asp:Xml': 'div',
    'asp:Substitution': 'span',
    'asp:Localize': 'span',
    'asp:MultiView': 'div',
    'asp:View': 'div',
    'asp:Wizard': 'div',
    'asp:FileUpload': 'input',
    'asp:HiddenField': 'input',
}

# ========== 属性映射 ==========
ATTR_MAP = {
    'Text': 'th:text',
    'ToolTip': 'title',
    'CssClass': 'class',
    'BackColor': 'style="background-color: {0}"',
    'ForeColor': 'style="color: {0}"',
    'Font-Size': 'style="font-size: {0}"',
    'Font-Bold': 'style="font-weight: {0}"',
    'Width': 'style="width: {0}"',
    'Height': 'style="height: {0}"',
    'BorderWidth': 'style="border-width: {0}"',
    'BorderColor': 'style="border-color: {0}"',
    'HorizontalAlign': 'style="text-align: {0}"',
    'VerticalAlign': 'style="vertical-align: {0}"',
    'NavigateUrl': 'th:href',
    'ImageUrl': 'th:src',
    'AlternateText': 'th:alt',
    'Enabled': 'th:disabled',
    'Visible': 'th:if',
    'ReadOnly': 'th:readonly',
    'MaxLength': 'maxlength',
    'Rows': 'rows',
    'Columns': 'cols',
    'Wrap': 'wrap',
    'SelectionMode': 'multiple' if 'Multiple' else None,
    'AutoPostBack': 'th:onchange',
    'OnClientClick': 'onclick',
    'DataTextField': 'th:text',
    'DataValueField': 'th:value',
    'DataSourceID': None,
    'DataKeyNames': None,
}

# 需要移除的属性
REMOVE_ATTRS = ['runat', 'ID', 'OnClick', 'OnLoad', 'OnInit', 'OnPreRender', 
                'OnDataBinding', 'OnItemDataBound', 'OnSelectedIndexChanged',
                'DataSourceID', 'AutoGenerateColumns', 'AutoGenerateEditButton',
                'AutoGenerateDeleteButton', 'AutoGenerateSelectButton']

# ========== 图片路径转换函数 ==========
def convert_image_path(path):
    """
    转换图片路径为 Thymeleaf 格式
    例如: ~/images/logo.png -> @{/images/logo.png}
          ../images/logo.png -> @{/images/logo.png}
          images/logo.png -> @{/images/logo.png}
    """
    if not path:
        return path
    
    original_path = path
    
    # 移除引号
    path = path.strip('"\'')
    
    # 应用路径映射
    for pattern, replacement in IMG_PATH_MAPPING.items():
        if re.search(pattern, path, re.IGNORECASE):
            # 替换路径并添加闭合括号
            new_path = re.sub(pattern, replacement, path, flags=re.IGNORECASE)
            # 如果 replacement 以 @{ 开头，需要添加 }
            if replacement.startswith('@{'):
                if not new_path.endswith('}'):
                    new_path += '}'
            return new_path
    
    # 如果路径包含图片扩展名，默认转换
    if re.search(r'\.(jpg|jpeg|png|gif|bmp|svg|webp)$', path, re.IGNORECASE):
        # 移除可能的前缀
        clean_path = re.sub(r'^[~\./]+', '', path)
        return f'@{{/images/{clean_path}}}'
    
    return path

# ========== 数据绑定表达式 ==========
def convert_data_binding(text, loop_var='item'):
    """转换数据绑定表达式"""
    # <%# Eval("Name") %> -> ${item.name}
    text = re.sub(r'<%#\s*Eval\(["\']([^"\']+)["\']\)\s*%>', 
                  rf'${{{loop_var}.get\1()}}', text, flags=re.IGNORECASE)
    # <%# Bind("Name") %> -> *{name}
    text = re.sub(r'<%#\s*Bind\(["\']([^"\']+)["\']\)\s*%>', 
                  rf'*{{{1.lower()}}}', text, flags=re.IGNORECASE)
    # <%# Container.DataItem %> -> ${item}
    text = re.sub(r'<%#\s*Container\.DataItem\s*%>', 
                  rf'${{{loop_var}}}', text, flags=re.IGNORECASE)
    # 简单表达式
    text = re.sub(r'<%#\s*([^%>]+)\s*%>', 
                  r'<!-- TODO: 原数据绑定 \1 -->', text, flags=re.IGNORECASE)
    return text

# ========== 处理 GridView ==========
def process_gridview(content):
    """处理 GridView 控件"""
    def replace_boundfield(match):
        header = match.group(1) or ''
        datafield = match.group(2)
        if header:
            return f'<th>{header}</th>'
        return f'<td th:text="${{item.{datafield}}}"></td>'
    
    def replace_templatefield(match):
        template = match.group(1)
        template = convert_data_binding(template)
        return template
    
    content = re.sub(r'<asp:BoundField\s+HeaderText="([^"]*)"\s+DataField="([^"]+)"[^>]*/>', 
                     replace_boundfield, content, flags=re.IGNORECASE)
    content = re.sub(r'<asp:TemplateField[^>]*>(.*?)</asp:TemplateField>', 
                     replace_templatefield, content, flags=re.DOTALL | re.IGNORECASE)
    return content

# ========== 处理 Repeater ==========
def process_repeater(match):
    """转换 Repeater 控件"""
    inner = match.group(1)
    item_match = re.search(r'<ItemTemplate>(.*?)</ItemTemplate>', inner, re.DOTALL | re.IGNORECASE)
    if item_match:
        template = item_match.group(1)
        template = convert_data_binding(template)
        # 检查是否有 DataSource 属性
        datasource = 'items'
        return f'<div th:each="item : ${{{datasource}}}">\n{template}\n</div>'
    return f'<!-- TODO: Repeater 需要手动处理 -->{inner}'

# ========== 处理 ListView ==========
def process_listview(match):
    """转换 ListView 控件"""
    inner = match.group(1)
    item_match = re.search(r'<ItemTemplate>(.*?)</ItemTemplate>', inner, re.DOTALL | re.IGNORECASE)
    layout_match = re.search(r'<LayoutTemplate>(.*?)</LayoutTemplate>', inner, re.DOTALL | re.IGNORECASE)
    
    if item_match:
        template = item_match.group(1)
        template = convert_data_binding(template)
        datasource = 'items'
        
        if layout_match:
            layout = layout_match.group(1)
            layout = re.sub(r'<asp:PlaceHolder[^>]*id="itemPlaceholder"[^>]*/>', 
                           f'<div th:each="item : ${{{datasource}}}">\n{template}\n</div>', 
                           layout, flags=re.IGNORECASE)
            return layout
        return f'<div th:each="item : ${{{datasource}}}">\n{template}\n</div>'
    return f'<!-- TODO: ListView 需要手动处理 -->{inner}'

# ========== 处理 DropDownList/ListBox ==========
def process_listcontrol(match):
    """转换 DropDownList/ListBox"""
    tag_name = match.group(1)
    attrs = match.group(2)
    inner = match.group(3) if match.lastindex >= 3 else ''
    
    datasource_match = re.search(r'DataSourceID\s*=\s*["\'](\w+)["\']', attrs, re.IGNORECASE)
    textfield_match = re.search(r'DataTextField\s*=\s*["\'](\w+)["\']', attrs, re.IGNORECASE)
    valuefield_match = re.search(r'DataValueField\s*=\s*["\'](\w+)["\']', attrs, re.IGNORECASE)
    
    new_tag = TAG_MAP.get(tag_name, 'select')
    
    # 静态选项
    options = ''
    option_matches = re.finditer(r'<asp:ListItem[^>]*Value="([^"]*)"[^>]*>(.*?)</asp:ListItem>', 
                                 inner, re.IGNORECASE)
    for opt in option_matches:
        value, text = opt.group(1), opt.group(2)
        options += f'<option value="{value}" th:text="{text}"></option>\n'
    
    # 动态数据绑定
    if datasource_match and textfield_match:
        datasource = datasource_match.group(1)
        textfield = textfield_match.group(1)
        valuefield = valuefield_match.group(1) if valuefield_match else 'Id'
        options = f'<option th:each="opt : ${{{datasource}}}" th:value="${{opt.{valuefield}}}" th:text="${{opt.{textfield}}}"></option>'
    
    return f'<{new_tag}>\n{options}</{new_tag}>'

# ========== 处理 CheckBoxList/RadioButtonList ==========
def process_checkboxlist(match):
    """转换 CheckBoxList/RadioButtonList"""
    tag_name = match.group(1)
    attrs = match.group(2)
    inner = match.group(3)
    
    input_type = 'checkbox' if 'CheckBox' in tag_name else 'radio'
    name_match = re.search(r'ID\s*=\s*["\'](\w+)["\']', attrs, re.IGNORECASE)
    name = name_match.group(1) if name_match else 'options'
    
    items = ''
    item_matches = re.finditer(r'<asp:ListItem[^>]*Value="([^"]*)"[^>]*>(.*?)</asp:ListItem>', 
                               inner, re.IGNORECASE)
    for item in item_matches:
        value, text = item.group(1), item.group(2)
        items += f'<label><input type="{input_type}" name="{name}" value="{value}" /> {text}</label><br/>\n'
    
    return f'<div>\n{items}</div>'

# ========== 处理验证控件 ==========
def process_validator(match):
    """转换验证控件"""
    tag_name = match.group(1)
    attrs = match.group(2)
    
    control_match = re.search(r'ControlToValidate\s*=\s*["\'](\w+)["\']', attrs, re.IGNORECASE)
    error_match = re.search(r'ErrorMessage\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    
    if control_match and error_match:
        field = control_match.group(1)
        message = error_match.group(1)
        return f'<span th:if="${{#fields.hasErrors(\'{field}\')}}" th:errors="*{{{field}}}" style="color: red;">{message}</span>'
    return f'<!-- TODO: 验证控件需要手动处理 -->'

# ========== 处理 ValidationSummary ==========
def process_validationsummary(match):
    """转换 ValidationSummary"""
    attrs = match.group(1)
    header_match = re.search(r'HeaderText\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    header = header_match.group(1) if header_match else '请更正以下错误'
    return f'''<div th:if="${{#fields.hasErrors()}}">
    <h3>{header}</h3>
    <ul>
        <li th:each="err : ${{#fields.allErrors()}}" th:text="${{err}}"></li>
    </ul>
</div>'''

# ========== 处理 HyperLink ==========
def process_hyperlink(match):
    """转换 HyperLink 控件"""
    attrs = match.group(1)
    text_match = re.search(r'Text\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    url_match = re.search(r'NavigateUrl\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    
    text = text_match.group(1) if text_match else 'link'
    url = url_match.group(1) if url_match else '#'
    # 转换 ~/ 为 @{}
    url = re.sub(r'~/(\w+)', r'@{/\1}', url)
    
    return f'<a th:href="{url}">{text}</a>'

# ========== 处理 Image（增强版，支持路径转换）==========
def process_image(match):
    """转换 Image 控件，并转换图片路径"""
    attrs = match.group(1)
    url_match = re.search(r'ImageUrl\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    alt_match = re.search(r'AlternateText\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    
    url = url_match.group(1) if url_match else ''
    alt = alt_match.group(1) if alt_match else ''
    
    # 转换图片路径
    url = convert_image_path(url)
    
    return f'<img th:src="{url}" alt="{alt}" />'

# ========== 主转换函数 ==========
def convert_aspx_to_thymeleaf(content):
    """完整的 ASPX 到 Thymeleaf 转换"""
    
    # 1. 移除指令
    content = re.sub(r'<%@\s*Page.*?%>', '', content, flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r'<%@\s*Master.*?%>', '', content, flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r'<%@\s*Register.*?%>', '', content, flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r'<%@\s*Assembly.*?%>', '', content, flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r'<%@\s*Import.*?%>', '', content, flags=re.DOTALL | re.IGNORECASE)
    
    # 2. 处理母版页
    content = re.sub(r'<asp:ContentPlaceHolder[^>]*ID="([^"]+)"[^>]*>', 
                     r'<div th:fragment="\1">', content, flags=re.IGNORECASE)
    content = re.sub(r'</asp:ContentPlaceHolder>', '</div>', content, flags=re.IGNORECASE)
    content = re.sub(r'<asp:Content[^>]*ContentPlaceHolderID="([^"]+)"[^>]*>', 
                     r'<div th:replace="~{layout :: \1}">', content, flags=re.IGNORECASE)
    content = re.sub(r'</asp:Content>', '</div>', content, flags=re.IGNORECASE)
    
    # 3. 处理数据控件
    content = re.sub(r'<asp:GridView[^>]*>(.*?)</asp:GridView>', 
                     lambda m: process_gridview(m.group(1)), content, flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r'<asp:Repeater[^>]*>(.*?)</asp:Repeater>', 
                     process_repeater, content, flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r'<asp:ListView[^>]*>(.*?)</asp:ListView>', 
                     process_listview, content, flags=re.DOTALL | re.IGNORECASE)
    
    # 4. 处理列表控件
    content = re.sub(r'<(asp:DropDownList|asp:ListBox)([^>]*)>(.*?)</\1>', 
                     process_listcontrol, content, flags=re.DOTALL | re.IGNORECASE)
    
    # 5. 处理 CheckBoxList/RadioButtonList
    content = re.sub(r'<(asp:CheckBoxList|asp:RadioButtonList)([^>]*)>(.*?)</\1>', 
                     process_checkboxlist, content, flags=re.DOTALL | re.IGNORECASE)
    
    # 6. 处理验证控件
    content = re.sub(r'<asp:RequiredFieldValidator[^>]*/?>', 
                     process_validator, content, flags=re.IGNORECASE)
    content = re.sub(r'<asp:ValidationSummary[^>]*/?>', 
                     process_validationsummary, content, flags=re.IGNORECASE)
    
    # 7. 处理导航控件
    content = re.sub(r'<asp:HyperLink([^>]*)/?>', process_hyperlink, content, flags=re.IGNORECASE)
    content = re.sub(r'<asp:Image([^>]*)/?>', process_image, content, flags=re.IGNORECASE)
    
    # 8. 处理通用标签
    tag_pattern = re.compile(r'<(asp:\w+)([^>]*?)(?:/>|>(.*?)</\1>)', re.IGNORECASE | re.DOTALL)
    
    def replace_general_tag(match):
        tag_name = match.group(1)
        attrs = match.group(2)
        inner = match.group(3) if match.lastindex >= 3 else ''
        
        new_tag = TAG_MAP.get(tag_name, 'div')
        
        # 处理属性
        new_attrs = []
        for attr_name, attr_val in re.findall(r'(\w+)\s*=\s*["\']([^"\']*)["\']', attrs):
            if attr_name in REMOVE_ATTRS:
                continue
            if attr_name in ATTR_MAP:
                mapping = ATTR_MAP[attr_name]
                if mapping is None:
                    continue
                if '{0}' in mapping:
                    new_attrs.append(mapping.format(attr_val))
                else:
                    new_attrs.append(f'{mapping}="{attr_val}"')
            elif attr_name.lower() in ['style', 'class', 'id', 'name']:
                new_attrs.append(f'{attr_name}="{attr_val}"')
        
        # 处理 Text 属性
        text_match = re.search(r'Text\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
        if text_match and not inner.strip():
            inner = text_match.group(1)
            new_attrs.append(f'th:text="${{{inner}}}"')
            inner = ''
        
        # 转换 inner 中的数据绑定
        inner = convert_data_binding(inner)
        
        attr_str = ' ' + ' '.join(new_attrs) if new_attrs else ''
        
        # 自闭合标签
        if tag_name in ['asp:Image', 'asp:HyperLink', 'asp:Xml'] or (not inner and new_tag in ['img', 'input', 'br', 'hr']):
            return f'<{new_tag}{attr_str} />'
        
        return f'<{new_tag}{attr_str}>\n{inner}\n</{new_tag}>'
    
    # 循环处理嵌套标签
    for _ in range(10):
        content = tag_pattern.sub(replace_general_tag, content)
    
    # 9. 移除残留的 runat="server"
    content = re.sub(r'\s+runat="server"', '', content, flags=re.IGNORECASE)
    
    # 10. 额外处理：转换所有图片标签的 src 属性（包括普通 img 标签）
    def convert_img_src(match):
        prefix = match.group(1)
        src = match.group(2)
        suffix = match.group(3)
        new_src = convert_image_path(src)
        return f'{prefix}th:src="{new_src}"{suffix}'
    
    content = re.sub(r'(<img\s+[^>]*?)(src=["\'])([^"\']+)(["\'])([^>]*?>)', 
                     convert_img_src, content, flags=re.IGNORECASE)
    
    # 11. 转换 CSS 中的 background-image
    def convert_bg_image(match):
        url = match.group(1)
        new_url = convert_image_path(url)
        return f'background-image: url({new_url})'
    
    content = re.sub(r'background-image:\s*url\(["\']?([^"\'\)]+)["\']?\)', 
                     convert_bg_image, content, flags=re.IGNORECASE)
    
    # 12. 转换脚本块
    content = re.sub(r'<script\s+runat="server"[^>]*>(.*?)</script>', 
                     r'<!-- 原服务器端脚本块已移除，请迁移到 Controller: \1 -->', 
                     content, flags=re.DOTALL | re.IGNORECASE)
    
    # 13. 添加 Thymeleaf 命名空间
    if '<html' in content.lower():
        content = re.sub(r'<html', '<html xmlns:th="http://www.thymeleaf.org"', content, count=1, flags=re.IGNORECASE)
    else:
        content = f'''<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8">
    <title>Converted Page</title>
</head>
<body>
{content}
</body>
</html>'''
    
    # 14. 添加警告注释
    warning = '''<!-- 
    ============================================
    警告：此文件由脚本自动生成，仍需大量人工处理：
    
    ✓ 已处理的控件：Label, TextBox, Button, DropDownList, GridView, Repeater, CheckBoxList, Validation 等
    ✓ 图片路径已自动转换：~/images/xxx -> @{/images/xxx}
    ✗ 需要手动处理的内容：
      1. 数据源绑定（DataSourceID）需要改为后端 Model 传递
      2. 事件处理（OnClick, OnLoad）需要迁移到 Controller
      3. ViewState 相关逻辑需要重新设计
      4. IsPostBack 需要拆分为 GET/POST 方法
      5. 文件上传控件需要特殊处理
      6. 第三方/自定义控件无法自动转换
    
    请根据实际业务逻辑进行调整！
    ============================================
    -->\n'''
    
    return warning + content

def main():
    if len(sys.argv) < 3:
        print("用法: python aspx2thymeleaf_full.py input.aspx output.html")
        print("支持编码: Shift-JIS (自动检测并转换)")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    # 读取文件（支持 Shift-JIS）
    encodings_to_try = [INPUT_ENCODING, 'cp932', 'shift_jis', 'shift-jis', 'utf-8', 'gbk']
    content = None
    used_encoding = None
    
    for enc in encodings_to_try:
        try:
            with open(input_file, 'r', encoding=enc) as f:
                content = f.read()
            used_encoding = enc
            print(f"成功使用编码: {enc}")
            break
        except (UnicodeDecodeError, LookupError) as e:
            continue
        except Exception as e:
            print(f"读取文件时出错 ({enc}): {e}")
            continue
    
    if content is None:
        print(f"错误: 无法读取文件 {input_file}，尝试了多种编码均失败。")
        print("请检查文件是否存在，或手动指定编码。")
        sys.exit(1)
    
    # 转换内容
    result = convert_aspx_to_thymeleaf(content)
    
    # 写入输出文件（UTF-8）
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(result)
    
    print(f"\n转换完成: {output_file}")
    print(f"输入编码: {used_encoding}")
    print(f"输出编码: UTF-8")
    print("\n请根据文件中的警告注释手动调整以下内容：")
    print("  - 数据源绑定 (DataSourceID → Model 属性)")
    print("  - 事件处理 (OnClick → Controller 方法)")
    print("  - IsPostBack 逻辑拆分")
    print("  - 图片路径已自动转换为 Thymeleaf 格式 (@{/images/...})")

if __name__ == '__main__':
    main()
