#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ASPX 到 Thymeleaf + Material Design 完整转换脚本
支持：Shift-JIS 编码、图片路径转换、Material Design 按钮、所有常见 asp 标签
用法: python aspx2thymeleaf_material.py input.aspx output.html
"""

import re
import sys
from pathlib import Path

# 尝试导入编解码器
try:
    import codecs
    codecs.lookup('shift-jis')
except LookupError:
    pass

# ========== 配置 ==========
INPUT_ENCODING = 'shift-jis'
OUTPUT_ENCODING = 'utf-8'

# Material Design 按钮类型映射（根据按钮样式或用途）
BUTTON_TYPE_MAP = {
    # 默认按钮类型
    'default': 'md-outlined-button',      # 边框按钮（次要操作）
    'primary': 'md-filled-button',         # 填充按钮（主要操作）
    'submit': 'md-filled-button',          # 提交按钮
    'cancel': 'md-outlined-button',        # 取消按钮
    'delete': 'md-text-button',            # 删除按钮（文字按钮）
    'danger': 'md-filled-button',          # 危险操作
    'icon': 'md-icon-button',              # 图标按钮
}

# 根据 CSS 类名或文本内容判断按钮类型
BUTTON_STYLE_RULES = [
    (r'btn-primary|primary|save|submit|登录|注册|提交|保存', 'primary'),
    (r'btn-danger|danger|delete|remove|删除|移除', 'delete'),
    (r'btn-cancel|cancel|取消|返回|back', 'cancel'),
    (r'btn-icon|icon-only', 'icon'),
]

# 图片路径配置
IMG_PATH_MAPPING = {
    r'~/images/': '@{/images/',
    r'~/img/': '@{/img/',
    r'~/Image/': '@{/image/',
    r'\.\./images/': '@{/images/',
    r'\.\./img/': '@{/img/',
    r'Images/': '@{/images/',
    r'images/': '@{/images/',
}

# ========== 标签映射表 ==========
TAG_MAP = {
    'asp:Label': 'span',
    'asp:TextBox': 'input',
    'asp:Button': 'button',  # 会被 Material 按钮替换
    'asp:LinkButton': 'a',
    'asp:ImageButton': 'button',
    'asp:HyperLink': 'a',
    'asp:Image': 'img',
    'asp:Panel': 'div',
    'asp:PlaceHolder': 'div',
    'asp:Literal': 'span',
    'asp:CheckBox': 'md-checkbox',
    'asp:RadioButton': 'md-radio',
    'asp:CheckBoxList': 'div',
    'asp:RadioButtonList': 'div',
    'asp:DropDownList': 'md-select',
    'asp:ListBox': 'md-select',
    'asp:BulletedList': 'ul',
    'asp:Table': 'table',
    'asp:TableRow': 'tr',
    'asp:TableCell': 'td',
    'asp:Repeater': 'div',
    'asp:GridView': 'table',
    'asp:DataList': 'div',
    'asp:ListView': 'div',
    'asp:RequiredFieldValidator': 'span',
    'asp:ValidationSummary': 'div',
    'asp:Menu': 'md-menu',
    'asp:FileUpload': 'input',
    'asp:HiddenField': 'input',
}

# 需要移除的属性
REMOVE_ATTRS = ['runat', 'ID', 'OnClick', 'OnLoad', 'OnInit', 'OnPreRender', 
                'OnDataBinding', 'OnItemDataBound', 'OnSelectedIndexChanged',
                'DataSourceID', 'AutoGenerateColumns', 'AutoGenerateEditButton',
                'AutoGenerateDeleteButton', 'AutoGenerateSelectButton']

# ========== Material 按钮转换函数 ==========
def get_button_type(attrs_text, inner_text=''):
    """
    根据按钮属性和文本内容判断应该使用哪种 Material 按钮类型
    """
    combined = f"{attrs_text} {inner_text}".lower()
    
    for pattern, btn_type in BUTTON_STYLE_RULES:
        if re.search(pattern, combined, re.IGNORECASE):
            return BUTTON_TYPE_MAP.get(btn_type, 'md-outlined-button')
    
    # 检查是否有 CssClass 属性
    css_match = re.search(r'CssClass\s*=\s*["\']([^"\']+)["\']', attrs_text, re.IGNORECASE)
    if css_match:
        css_classes = css_match.group(1).lower()
        for pattern, btn_type in BUTTON_STYLE_RULES:
            if re.search(pattern, css_classes):
                return BUTTON_TYPE_MAP.get(btn_type, 'md-outlined-button')
    
    # 默认使用 outlined button
    return 'md-outlined-button'

def convert_button_to_material(match):
    """
    将 ASP.NET Button 转换为 Material Design 按钮
    """
    tag_name = match.group(1)
    attrs = match.group(2)
    inner = match.group(3) if match.lastindex >= 3 and match.group(3) else ''
    
    # 提取按钮属性
    text = ''
    text_match = re.search(r'Text\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    if text_match:
        text = text_match.group(1)
    
    # 提取 CSS 类
    css_class = ''
    css_match = re.search(r'CssClass\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    if css_match:
        css_class = css_match.group(1)
    
    # 提取 OnClick 事件（转换为 th:action 或留在 data 属性中）
    onclick = ''
    onclick_match = re.search(r'OnClick\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    if onclick_match:
        onclick = onclick_match.group(1)
    
    # 判断按钮类型
    btn_material_type = get_button_type(attrs, text)
    
    # 构建 Material 按钮属性
    material_attrs = []
    
    # 添加类型属性
    material_attrs.append('type="button"')
    
    # 如果是提交按钮
    if 'submit' in btn_material_type or re.search(r'submit|登录|注册|保存', text + attrs, re.IGNORECASE):
        material_attrs.append('type="submit"')
    
    # 添加 CSS 类（保留原始类）
    if css_class:
        material_attrs.append(f'class="{css_class}"')
    
    # 添加 Thymeleaf 事件处理
    if onclick:
        material_attrs.append(f'th:click="@{{{onclick}}}"')
        material_attrs.append(f'data-original-onclick="{onclick}"')
    
    # 添加禁用状态
    if re.search(r'Enabled\s*=\s*["\']false["\']', attrs, re.IGNORECASE):
        material_attrs.append('disabled')
    
    # 构建最终标签
    attrs_str = ' ' + ' '.join(material_attrs) if material_attrs else ''
    
    # 按钮文本（如果标签内没有内容，使用 Text 属性）
    if not inner.strip() and text:
        button_text = text
    else:
        button_text = inner
    
    # 转义可能存在的表达式
    button_text = convert_data_binding(button_text)
    
    # 如果是图标按钮，添加图标
    if btn_material_type == 'md-icon-button':
        # 图标按钮使用 slot="icon"
        return f'''<{btn_material_type}{attrs_str}>
    <md-icon slot="icon">{button_text or 'favorite'}</md-icon>
</{btn_material_type}>'''
    
    # 普通按钮
    return f'<{btn_material_type}{attrs_str}>{button_text}</{btn_material_type}>'

def convert_linkbutton_to_material(match):
    """
    将 ASP.NET LinkButton 转换为 Material Design 链接按钮
    """
    attrs = match.group(1)
    inner = match.group(2) if match.lastindex >= 2 else ''
    
    # 提取属性
    text = ''
    text_match = re.search(r'Text\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    if text_match:
        text = text_match.group(1)
    
    # 提取 PostBackUrl
    postback_url = ''
    url_match = re.search(r'PostBackUrl\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    if url_match:
        postback_url = url_match.group(1)
    
    button_text = text if text else inner
    button_text = convert_data_binding(button_text)
    
    # 使用 text button 样式
    return f'<md-text-button th:href="@{{{postback_url}}}" onclick="return false;">{button_text}</md-text-button>'

def convert_imagebutton_to_material(match):
    """
    将 ASP.NET ImageButton 转换为带图标的 Material 按钮
    """
    attrs = match.group(1)
    
    # 提取图片 URL
    img_url = ''
    img_match = re.search(r'ImageUrl\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    if img_match:
        img_url = convert_image_path(img_match.group(1))
    
    # 提取 AlternateText
    alt_text = ''
    alt_match = re.search(r'AlternateText\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    if alt_match:
        alt_text = alt_match.group(1)
    
    # 提取 OnClick
    onclick = ''
    onclick_match = re.search(r'OnClick\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    if onclick_match:
        onclick = onclick_match.group(1)
    
    return f'''<md-filled-button th:click="@{{{onclick}}}" aria-label="{alt_text}">
    <md-icon slot="icon">
        <img th:src="{img_url}" alt="{alt_text}" style="width: 24px; height: 24px;" />
    </md-icon>
    {alt_text}
</md-filled-button>'''

# ========== 图片路径转换 ==========
def convert_image_path(path):
    if not path:
        return path
    
    path = path.strip('"\'')
    
    for pattern, replacement in IMG_PATH_MAPPING.items():
        if re.search(pattern, path, re.IGNORECASE):
            new_path = re.sub(pattern, replacement, path, flags=re.IGNORECASE)
            if replacement.startswith('@{') and not new_path.endswith('}'):
                new_path += '}'
            return new_path
    
    if re.search(r'\.(jpg|jpeg|png|gif|bmp|svg|webp)$', path, re.IGNORECASE):
        clean_path = re.sub(r'^[~\./]+', '', path)
        return f'@{{/images/{clean_path}}}'
    
    return path

# ========== 数据绑定表达式 ==========
def convert_data_binding(text, loop_var='item'):
    if not text:
        return text
    
    text = re.sub(r'<%#\s*Eval\(["\']([^"\']+)["\']\)\s*%>', 
                  rf'${{{loop_var}.get\1()}}', text, flags=re.IGNORECASE)
    text = re.sub(r'<%#\s*Bind\(["\']([^"\']+)["\']\)\s*%>', 
                  rf'*{{{1.lower()}}}', text, flags=re.IGNORECASE)
    text = re.sub(r'<%#\s*Container\.DataItem\s*%>', 
                  rf'${{{loop_var}}}', text, flags=re.IGNORECASE)
    text = re.sub(r'<%#\s*([^%>]+)\s*%>', 
                  r'<!-- TODO: 原数据绑定 \1 -->', text, flags=re.IGNORECASE)
    return text

# ========== 处理其他控件 ==========
def process_image(match):
    attrs = match.group(1)
    url_match = re.search(r'ImageUrl\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    alt_match = re.search(r'AlternateText\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    
    url = url_match.group(1) if url_match else ''
    alt = alt_match.group(1) if alt_match else ''
    url = convert_image_path(url)
    
    return f'<img th:src="{url}" alt="{alt}" />'

def process_checkbox(match):
    attrs = match.group(1)
    text_match = re.search(r'Text\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    text = text_match.group(1) if text_match else ''
    
    return f'''<md-checkbox>
    <span slot="label">{convert_data_binding(text)}</span>
</md-checkbox>'''

def process_radiobutton(match):
    attrs = match.group(1)
    text_match = re.search(r'Text\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    group_match = re.search(r'GroupName\s*=\s*["\']([^"\']+)["\']', attrs, re.IGNORECASE)
    
    text = text_match.group(1) if text_match else ''
    group = group_match.group(1) if group_match else 'radio-group'
    
    return f'''<md-radio name="{group}">
    <span slot="label">{convert_data_binding(text)}</span>
</md-radio>'''

def process_dropdown(match):
    tag_name = match.group(1)
    attrs = match.group(2)
    inner = match.group(3) if match.lastindex >= 3 else ''
    
    options = ''
    option_matches = re.finditer(r'<asp:ListItem[^>]*Value="([^"]*)"[^>]*>(.*?)</asp:ListItem>', 
                                 inner, re.IGNORECASE)
    for opt in option_matches:
        value, text = opt.group(1), opt.group(2)
        options += f'<md-option value="{value}">{text}</md-option>\n'
    
    return f'<md-select>\n{options}</md-select>'

# ========== 主转换函数 ==========
def add_material_dependencies(html_content):
    """添加 Material Web Components 的依赖"""
    material_imports = '''<!-- Material Web Components -->
<script type="module" src="https://unpkg.com/@material/web@1.0.0/index.js"></script>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
<style>
    body {
        font-family: 'Roboto', sans-serif;
        margin: 0;
        padding: 0;
    }
    md-filled-button, md-outlined-button, md-text-button, md-icon-button {
        margin: 4px;
    }
</style>
'''
    
    # 在 head 标签内添加依赖
    if '<head>' in html_content:
        html_content = html_content.replace('<head>', f'<head>\n{material_imports}')
    else:
        html_content = html_content.replace('<html', f'<html>\n<head>\n{material_imports}\n</head>')
    
    return html_content

def convert_aspx_to_thymeleaf(content):
    """完整的 ASPX 到 Thymeleaf + Material Design 转换"""
    
    # 移除指令
    content = re.sub(r'<%@\s*Page.*?%>', '', content, flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r'<%@\s*Master.*?%>', '', content, flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r'<%@\s*Register.*?%>', '', content, flags=re.DOTALL | re.IGNORECASE)
    
    # 处理母版页
    content = re.sub(r'<asp:ContentPlaceHolder[^>]*ID="([^"]+)"[^>]*>', 
                     r'<div th:fragment="\1">', content, flags=re.IGNORECASE)
    content = re.sub(r'</asp:ContentPlaceHolder>', '</div>', content, flags=re.IGNORECASE)
    
    # 转换按钮（必须在通用标签之前）
    content = re.sub(r'<asp:Button([^>]*?)(?:/>|>(.*?)</asp:Button>)', 
                     convert_button_to_material, content, flags=re.DOTALL | re.IGNORECASE)
    
    # 转换 LinkButton
    content = re.sub(r'<asp:LinkButton([^>]*?)(?:/>|>(.*?)</asp:LinkButton>)', 
                     convert_linkbutton_to_material, content, flags=re.DOTALL | re.IGNORECASE)
    
    # 转换 ImageButton
    content = re.sub(r'<asp:ImageButton([^>]*?)/?>', 
                     convert_imagebutton_to_material, content, flags=re.DOTALL | re.IGNORECASE)
    
    # 转换 CheckBox 和 RadioButton
    content = re.sub(r'<asp:CheckBox([^>]*?)(?:/>|>(.*?)</asp:CheckBox>)', 
                     process_checkbox, content, flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r'<asp:RadioButton([^>]*?)(?:/>|>(.*?)</asp:RadioButton>)', 
                     process_radiobutton, content, flags=re.DOTALL | re.IGNORECASE)
    
    # 转换 DropDownList
    content = re.sub(r'<(asp:DropDownList|asp:ListBox)([^>]*)>(.*?)</\1>', 
                     process_dropdown, content, flags=re.DOTALL | re.IGNORECASE)
    
    # 转换 Image
    content = re.sub(r'<asp:Image([^>]*?)/?>', process_image, content, flags=re.IGNORECASE)
    
    # 通用标签转换
    tag_pattern = re.compile(r'<(asp:\w+)([^>]*?)(?:/>|>(.*?)</\1>)', re.IGNORECASE | re.DOTALL)
    
    def replace_general_tag(match):
        tag_name = match.group(1)
        attrs = match.group(2)
        inner = match.group(3) if match.lastindex >= 3 else ''
        
        new_tag = TAG_MAP.get(tag_name, 'div')
        
        # 处理属性
        new_attrs = []
        for attr_name, attr_val in re.findall(r'(\w+)\s*=\s*["\']([^"\']*)["\']', attrs):
            if attr_name in REMOVE_ATTRS:
                continue
            if attr_name == 'Text' and new_tag in ['span', 'label']:
                new_attrs.append(f'th:text="${{{attr_val}}}"')
            elif attr_name == 'CssClass':
                new_attrs.append(f'class="{attr_val}"')
            elif attr_name not in ['ID', 'runat']:
                new_attrs.append(f'{attr_name.lower()}="{attr_val}"')
        
        inner = convert_data_binding(inner)
        attr_str = ' ' + ' '.join(new_attrs) if new_attrs else ''
        
        return f'<{new_tag}{attr_str}>\n{inner}\n</{new_tag}>'
    
    for _ in range(10):
        content = tag_pattern.sub(replace_general_tag, content)
    
    # 移除残留属性
    content = re.sub(r'\s+runat="server"', '', content, flags=re.IGNORECASE)
    
    # 转换图片 src
    def convert_img_src(match):
        prefix = match.group(1)
        src = match.group(2)
        suffix = match.group(3)
        new_src = convert_image_path(src)
        return f'{prefix}th:src="{new_src}"{suffix}'
    
    content = re.sub(r'(<img\s+[^>]*?)(src=["\'])([^"\']+)(["\'])([^>]*?>)', 
                     convert_img_src, content, flags=re.IGNORECASE)
    
    # 添加 Thymeleaf 命名空间
    if '<html' not in content.lower():
        content = f'''<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8">
    <title>Converted Page</title>
</head>
<body>
{content}
</body>
</html>'''
    else:
        content = re.sub(r'<html', '<html xmlns:th="http://www.thymeleaf.org"', content, count=1, flags=re.IGNORECASE)
    
    # 添加 Material Design 依赖
    content = add_material_dependencies(content)
    
    # 添加警告注释
    warning = '''<!-- 
    ============================================
    此文件由脚本自动生成，已转换：
    ✓ 所有按钮已转换为 Material Design 组件
      - asp:Button → md-outlined-button / md-filled-button
      - asp:LinkButton → md-text-button
      - asp:ImageButton → md-filled-button + 图标
    ✓ 图片路径已转换为 Thymeleaf 格式
    ✓ CheckBox/RadioButton → md-checkbox/md-radio
    
    需要手动处理：
    1. 按钮的 OnClick 事件需要迁移到 Controller
    2. 数据绑定 (DataSourceID) 需要后端 Model 传递
    3. IsPostBack 逻辑需要拆分为 GET/POST
    4. 验证控件需要配合 Hibernate Validation
    ============================================
    -->\n'''
    
    return warning + content

def main():
    if len(sys.argv) < 3:
        print("用法: python aspx2thymeleaf_material.py input.aspx output.html")
        print("支持: Shift-JIS 编码、Material Design 按钮、图片路径转换")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    # 读取文件（支持多种编码）
    encodings_to_try = [INPUT_ENCODING, 'cp932', 'shift_jis', 'shift-jis', 'utf-8', 'gbk']
    content = None
    used_encoding = None
    
    for enc in encodings_to_try:
        try:
            with open(input_file, 'r', encoding=enc) as f:
                content = f.read()
            used_encoding = enc
            print(f"成功读取文件，使用编码: {enc}")
            break
        except (UnicodeDecodeError, LookupError):
            continue
        except Exception as e:
            print(f"读取错误 ({enc}): {e}")
            continue
    
    if content is None:
        print(f"错误: 无法读取文件 {input_file}")
        sys.exit(1)
    
    # 转换
    result = convert_aspx_to_thymeleaf(content)
    
    # 写入
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(result)
    
    print(f"\n✓ 转换完成: {output_file}")
    print(f"  输入编码: {used_encoding}")
    print(f"  输出编码: UTF-8")
    print("\n按钮转换规则：")
    print("  - 普通按钮 → <md-outlined-button>")
    print("  - 主要操作(保存/提交/登录) → <md-filled-button>")
    print("  - 删除/危险操作 → <md-text-button>")
    print("  - 链接按钮 → <md-text-button>")

if __name__ == '__main__':
    main()
